version: "3"

services:
  rabbitmq:
    image: "rabbitmq"
    hostname: "rabbitmq"
    networks:
      - task1

  producer:
    build: producer
    networks:
      - task1
    depends_on:
      - rabbitmq

  consumer:
    build: consumer
    networks:
      - task1
    depends_on:
      - rabbitmq

networks:
  task1:
    driver: bridge
